-- begin CONFLICT_OF_INTEREST
alter table CONFLICT_OF_INTEREST add constraint FK_CONFLICT_OF_INTEREST_ON_PLAN_EVENT foreign key (PLAN_EVENT_ID) references PLAN_EVENT(ID)^
alter table CONFLICT_OF_INTEREST add constraint FK_CONFLICT_OF_INTEREST_ON_RISK_LEVEL foreign key (RISK_LEVEL_ID) references RISK_LEVEL(ID)^
create index IDX_CONFLICT_OF_INTEREST_ON_PLAN_EVENT on CONFLICT_OF_INTEREST (PLAN_EVENT_ID)^
create index IDX_CONFLICT_OF_INTEREST_ON_RISK_LEVEL on CONFLICT_OF_INTEREST (RISK_LEVEL_ID)^
create index IDX_CONFLICT_OF_INTEREST_PLAN_EVENT on CONFLICT_OF_INTEREST (PLAN_EVENT_ID)^
create index IDX_CONFLICT_OF_INTEREST_RISK_LEVEL on CONFLICT_OF_INTEREST (RISK_LEVEL_ID)^
-- end CONFLICT_OF_INTEREST
-- begin COMPLAINT_WORD_SETTING
alter table COMPLAINT_WORD_SETTING add constraint FK_COMPLAINT_WORD_SETTING_ON_COMPLAINT_REASON foreign key (COMPLAINT_REASON_ID) references COMPLAINT_REASON(ID)^
create index IDX_COMPLAINT_WORD_SETTING_ON_COMPLAINT_REASON on COMPLAINT_WORD_SETTING (COMPLAINT_REASON_ID)^
-- end COMPLAINT_WORD_SETTING
-- begin COMPLAINT_ANALYSIS_LOG
alter table COMPLAINT_ANALYSIS_LOG add constraint FK_COMPLAINT_ANALYSIS_LOG_ON_COMPLAINT foreign key (COMPLAINT_ID) references COMPLAINT(ID)^
alter table COMPLAINT_ANALYSIS_LOG add constraint FK_COMPLAINT_ANALYSIS_LOG_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_COMPLAINT_ANALYSIS_LOG_ON_COMPLAINT on COMPLAINT_ANALYSIS_LOG (COMPLAINT_ID)^
create index IDX_COMPLAINT_ANALYSIS_LOG_ON_USER on COMPLAINT_ANALYSIS_LOG (USER_ID)^
create index IDX_COMPLAINT_ANALYSIS_LOG_USER on COMPLAINT_ANALYSIS_LOG (USER_ID)^
create index IDX_COMPLAINT_ANALYSIS_LOG_COMPLAINT on COMPLAINT_ANALYSIS_LOG (COMPLAINT_ID)^
-- end COMPLAINT_ANALYSIS_LOG
-- begin CONTROL_MEASURE_ASSESSMENT
alter table CONTROL_MEASURE_ASSESSMENT add constraint FK_CONTROL_MEASURE_ASSESSMENT_ON_CONTROL_MEASURE_NAME foreign key (CONTROL_MEASURE_NAME_ID) references CONTROL_MEASURES(ID)^
alter table CONTROL_MEASURE_ASSESSMENT add constraint FK_CONTROL_MEASURE_ASSESSMENT_ON_MEASURE_PLAN foreign key (MEASURE_PLAN_ID) references PLAN_EVENT(ID)^
alter table CONTROL_MEASURE_ASSESSMENT add constraint FK_CONTROL_MEASURE_ASSESSMENT_ON_RESPONSIBLE_EXECUTOR foreign key (RESPONSIBLE_EXECUTOR_ID) references SEC_USER(ID)^
alter table CONTROL_MEASURE_ASSESSMENT add constraint FK_CONTROL_MEASURE_ASSESSMENT_ON_SELF_ASSESSMENT_SVK foreign key (SELF_ASSESSMENT_SVK_ID) references SELF_ASSESSMENT_SVK(ID)^
create index IDX_CONTROL_MEASURE_ASSESSMENT_ON_CONTROL_MEASURE_NAME on CONTROL_MEASURE_ASSESSMENT (CONTROL_MEASURE_NAME_ID)^
create index IDX_CONTROL_MEASURE_ASSESSMENT_ON_MEASURE_PLAN on CONTROL_MEASURE_ASSESSMENT (MEASURE_PLAN_ID)^
create index IDX_CONTROL_MEASURE_ASSESSMENT_ON_RESPONSIBLE_EXECUTOR on CONTROL_MEASURE_ASSESSMENT (RESPONSIBLE_EXECUTOR_ID)^
create index IDX_CONTROL_MEASURE_ASSESSMENT_ON_SELF_ASSESSMENT_SVK on CONTROL_MEASURE_ASSESSMENT (SELF_ASSESSMENT_SVK_ID)^
create index IDX_CONTROL_MEASURE_ASSESSMENT_MEASURE_PLAN on CONTROL_MEASURE_ASSESSMENT (MEASURE_PLAN_ID)^
create index IDX_CONTROL_MEASURE_ASSESSMENT_CONTROL_MEASURE_NAME on CONTROL_MEASURE_ASSESSMENT (CONTROL_MEASURE_NAME_ID)^
create index IDX_CONTROL_MEASURE_ASSESSMENT_SELF_ASSESSMENT_SVK on CONTROL_MEASURE_ASSESSMENT (SELF_ASSESSMENT_SVK_ID)^
create index IDX_CONTROL_MEASURE_ASSESSMENT_RESPONSIBLE_EXECUTOR on CONTROL_MEASURE_ASSESSMENT (RESPONSIBLE_EXECUTOR_ID)^
-- end CONTROL_MEASURE_ASSESSMENT
-- begin COMPLAINT
alter table COMPLAINT add constraint FK_COMPLAINT_ON_CHANNEL foreign key (CHANNEL_ID) references CHANNEL(ID)^
alter table COMPLAINT add constraint FK_COMPLAINT_ON_APPLICANT_TYPE foreign key (APPLICANT_TYPE_ID) references APPLICANT_TYPE(ID)^
alter table COMPLAINT add constraint FK_COMPLAINT_ON_CLIENT_PH foreign key (CLIENT_PH_ID) references CLIENT_PH(ID)^
alter table COMPLAINT add constraint FK_COMPLAINT_ON_REASON foreign key (REASON_ID) references SUBJECT(ID)^
alter table COMPLAINT add constraint FK_COMPLAINT_ON_CLOSED_BY_LOGIN foreign key (CLOSED_BY_LOGIN_ID) references SEC_USER(ID)^
alter table COMPLAINT add constraint FK_COMPLAINT_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references SEC_USER(ID)^
alter table COMPLAINT add constraint FK_COMPLAINT_ON_RESPONSE_TYPE foreign key (RESPONSE_TYPE_ID) references RESPONSE_TYPE(ID)^
alter table COMPLAINT add constraint FK_COMPLAINT_ON_COMPLAINT_REASON foreign key (COMPLAINT_REASON_ID) references COMPLAINT_REASON(ID)^
alter table COMPLAINT add constraint FK_COMPLAINT_ON_RISK_ASSESSMENT foreign key (RISK_ASSESSMENT_ID) references COMPLIANCE_RISK_ASSESSMENT(ID)^
create index IDX_COMPLAINT_ON_CHANNEL on COMPLAINT (CHANNEL_ID)^
create index IDX_COMPLAINT_ON_APPLICANT_TYPE on COMPLAINT (APPLICANT_TYPE_ID)^
create index IDX_COMPLAINT_ON_CLIENT_PH on COMPLAINT (CLIENT_PH_ID)^
create index IDX_COMPLAINT_ON_REASON on COMPLAINT (REASON_ID)^
create index IDX_COMPLAINT_ON_CLOSED_BY_LOGIN on COMPLAINT (CLOSED_BY_LOGIN_ID)^
create index IDX_COMPLAINT_ON_EMPLOYEE on COMPLAINT (EMPLOYEE_ID)^
create index IDX_COMPLAINT_ON_RESPONSE_TYPE on COMPLAINT (RESPONSE_TYPE_ID)^
create index IDX_COMPLAINT_ON_COMPLAINT_REASON on COMPLAINT (COMPLAINT_REASON_ID)^
create index IDX_COMPLAINT_ON_RISK_ASSESSMENT on COMPLAINT (RISK_ASSESSMENT_ID)^
create index IDX_COMPLAINT_EMPLOYEE on COMPLAINT (EMPLOYEE_ID)^
create index IDX_COMPLAINT_CLOSED_BY_LOGIN on COMPLAINT (CLOSED_BY_LOGIN_ID)^
create index IDX_COMPLAINT_CHANNEL on COMPLAINT (CHANNEL_ID)^
create index IDX_COMPLAINT_APPLICANT_TYPE on COMPLAINT (APPLICANT_TYPE_ID)^
create index IDX_COMPLAINT_COMPLAINT_REASON on COMPLAINT (COMPLAINT_REASON_ID)^
create index IDX_COMPLAINT_RESPONSE_TYPE on COMPLAINT (RESPONSE_TYPE_ID)^
create index IDX_COMPLAINT_RISK_ASSESSMENT on COMPLAINT (RISK_ASSESSMENT_ID)^
create index IDX_COMPLAINT_CLIENT_PH on COMPLAINT (CLIENT_PH_ID)^
create index IDX_COMPLAINT_REASON on COMPLAINT (REASON_ID)^
create index IDX_COMPLAINT_INITIATOR on COMPLAINT (INITIATOR)^
-- end COMPLAINT
-- begin COMPLIANCE_LAW_ACT
alter table COMPLIANCE_LAW_ACT add constraint FK_COMPLIANCE_LAW_ACT_ON_COMPLIANCE_LAW foreign key (COMPLIANCE_LAW_ID) references COMPLIANCE_LAW(ID)^
alter table COMPLIANCE_LAW_ACT add constraint FK_COMPLIANCE_LAW_ACT_ON_ACT foreign key (ACT_ID) references ACT(ID)^
create index IDX_COMPLIANCE_LAW_ACT_ON_COMPLIANCE_LAW on COMPLIANCE_LAW_ACT (COMPLIANCE_LAW_ID)^
create index IDX_COMPLIANCE_LAW_ACT_ON_ACT on COMPLIANCE_LAW_ACT (ACT_ID)^
create index IDX_COMPLIANCE_LAW_ACT_COMPLIANCE_LAW on COMPLIANCE_LAW_ACT (COMPLIANCE_LAW_ID)^
create index IDX_COMPLIANCE_LAW_ACT_ACT on COMPLIANCE_LAW_ACT (ACT_ID)^
-- end COMPLIANCE_LAW_ACT
-- begin DEPARTMENT
alter table DEPARTMENT add constraint FK_DEPARTMENT_ON_PARENT foreign key (PARENT_ID) references DEPARTMENT(ID)^
create index IDX_DEPARTMENT_ON_PARENT on DEPARTMENT (PARENT_ID)^
create index IDX_DEPARTMENT_PARENT on DEPARTMENT (PARENT_ID)^
-- end DEPARTMENT
-- begin INTERNAL_CONTROL_MONITORING
alter table INTERNAL_CONTROL_MONITORING add constraint FK_INTERNAL_CONTROL_MONITORING_ON_RESPONSIBLE_USER foreign key (RESPONSIBLE_USER_ID) references SEC_USER(ID)^
alter table INTERNAL_CONTROL_MONITORING add constraint FK_INTERNAL_CONTROL_MONITORING_ON_SELF_ASSESSMENT_SVK foreign key (SELF_ASSESSMENT_SVK_ID) references SELF_ASSESSMENT_SVK(ID)^
create index IDX_INTERNAL_CONTROL_MONITORING_ON_RESPONSIBLE_USER on INTERNAL_CONTROL_MONITORING (RESPONSIBLE_USER_ID)^
create index IDX_INTERNAL_CONTROL_MONITORING_ON_SELF_ASSESSMENT_SVK on INTERNAL_CONTROL_MONITORING (SELF_ASSESSMENT_SVK_ID)^
create index IDX_INTERNAL_CONTROL_MONITORING_SELF_ASSESSMENT_SVK on INTERNAL_CONTROL_MONITORING (SELF_ASSESSMENT_SVK_ID)^
create index IDX_INTERNAL_CONTROL_MONITORING_RESPONSIBLE_USER on INTERNAL_CONTROL_MONITORING (RESPONSIBLE_USER_ID)^
-- end INTERNAL_CONTROL_MONITORING
-- begin PRODUCT_SERVICE
alter table PRODUCT_SERVICE add constraint FK_PRODUCT_SERVICE_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references DEPARTMENT(ID)^
alter table PRODUCT_SERVICE add constraint FK_PRODUCT_SERVICE_ON_OWNER foreign key (OWNER_ID) references SEC_USER(ID)^
alter table PRODUCT_SERVICE add constraint FK_PRODUCT_SERVICE_ON_RISK_COORDINATOR foreign key (RISK_COORDINATOR_ID) references SEC_USER(ID)^
alter table PRODUCT_SERVICE add constraint FK_PRODUCT_SERVICE_ON_TYPE foreign key (TYPE_ID) references TYPE_(ID)^
create index IDX_PRODUCT_SERVICE_ON_DEPARTMENT on PRODUCT_SERVICE (DEPARTMENT_ID)^
create index IDX_PRODUCT_SERVICE_ON_OWNER on PRODUCT_SERVICE (OWNER_ID)^
create index IDX_PRODUCT_SERVICE_ON_RISK_COORDINATOR on PRODUCT_SERVICE (RISK_COORDINATOR_ID)^
create index IDX_PRODUCT_SERVICE_ON_TYPE on PRODUCT_SERVICE (TYPE_ID)^
create index IDX_PRODUCT_SERVICE_RISK_COORDINATOR on PRODUCT_SERVICE (RISK_COORDINATOR_ID)^
create index IDX_PRODUCT_SERVICE_DEPARTMENT on PRODUCT_SERVICE (DEPARTMENT_ID)^
create index IDX_PRODUCT_SERVICE_OWNER on PRODUCT_SERVICE (OWNER_ID)^
create index IDX_PRODUCT_SERVICE_TYPE on PRODUCT_SERVICE (TYPE_ID)^
-- end PRODUCT_SERVICE
-- begin ACTIVITY
alter table ACTIVITY add constraint FK_ACTIVITY_ON_PLAN_EVENT foreign key (PLAN_EVENT_ID) references PLAN_EVENT(ID)^
alter table ACTIVITY add constraint FK_ACTIVITY_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references DEPARTMENT(ID)^
create index IDX_ACTIVITY_ON_PLAN_EVENT on ACTIVITY (PLAN_EVENT_ID)^
create index IDX_ACTIVITY_ON_DEPARTMENT on ACTIVITY (DEPARTMENT_ID)^
create index IDX_ACTIVITY_PLAN_EVENT on ACTIVITY (PLAN_EVENT_ID)^
create index IDX_ACTIVITY_DEPARTMENT on ACTIVITY (DEPARTMENT_ID)^
-- end ACTIVITY
-- begin FILE_ENTITY
alter table FILE_ENTITY add constraint FK_FILE_ENTITY_ON_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID)^
create index IDX_FILE_ENTITY_ON_FILE_DESCRIPTOR on FILE_ENTITY (FILE_DESCRIPTOR_ID)^
-- end FILE_ENTITY
-- begin RISK_EVENT
alter table RISK_EVENT add constraint FK_RISK_EVENT_ON_SELF_ASSESSMENT_SVK foreign key (SELF_ASSESSMENT_SVK_ID) references SELF_ASSESSMENT_SVK(ID)^
alter table RISK_EVENT add constraint FK_RISK_EVENT_ON_PLAN_EVENT foreign key (PLAN_EVENT_ID) references ACTIVITY(ID)^
create index IDX_RISK_EVENT_ON_SELF_ASSESSMENT_SVK on RISK_EVENT (SELF_ASSESSMENT_SVK_ID)^
create index IDX_RISK_EVENT_ON_PLAN_EVENT on RISK_EVENT (PLAN_EVENT_ID)^
create index IDX_RISK_EVENT_PLAN_EVENT on RISK_EVENT (PLAN_EVENT_ID)^
create index IDX_RISK_EVENT_SELF_ASSESSMENT_SVK on RISK_EVENT (SELF_ASSESSMENT_SVK_ID)^
-- end RISK_EVENT
-- begin INCIDENTS
alter table INCIDENTS add constraint FK_INCIDENTS_ON_HEAD foreign key (HEAD_ID) references SEC_USER(ID)^
alter table INCIDENTS add constraint FK_INCIDENTS_ON_EXECUTOR foreign key (EXECUTOR_ID) references SEC_USER(ID)^
alter table INCIDENTS add constraint FK_INCIDENTS_ON_SOURCE foreign key (SOURCE_ID) references SOURCE_DICTIONARY(ID)^
create index IDX_INCIDENTS_ON_HEAD on INCIDENTS (HEAD_ID)^
create index IDX_INCIDENTS_ON_EXECUTOR on INCIDENTS (EXECUTOR_ID)^
create index IDX_INCIDENTS_ON_SOURCE on INCIDENTS (SOURCE_ID)^
create index IDX_INCIDENTS_HEAD on INCIDENTS (HEAD_ID)^
create index IDX_INCIDENTS_SOURCE on INCIDENTS (SOURCE_ID)^
create index IDX_INCIDENTS_EXECUTOR on INCIDENTS (EXECUTOR_ID)^
-- end INCIDENTS
-- begin COMPLIANCE_RISK
alter table COMPLIANCE_RISK add constraint FK_COMPLIANCE_RISK_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references DEPARTMENT(ID)^
alter table COMPLIANCE_RISK add constraint FK_COMPLIANCE_RISK_ON_RISK_CATEGORY foreign key (RISK_CATEGORY_ID) references RISK_LEVEL(ID)^
alter table COMPLIANCE_RISK add constraint FK_COMPLIANCE_RISK_ON_SOURCE foreign key (SOURCE_ID) references RISK_SOURCE(ID)^
alter table COMPLIANCE_RISK add constraint FK_COMPLIANCE_RISK_ON_RATING foreign key (RATING_ID) references RISK_LEVEL(ID)^
alter table COMPLIANCE_RISK add constraint FK_COMPLIANCE_RISK_ON_PLAN_EVENT foreign key (PLAN_EVENT_ID) references PLAN_EVENT(ID)^
alter table COMPLIANCE_RISK add constraint FK_COMPLIANCE_RISK_ON_OWNER foreign key (OWNER_ID) references SEC_USER(ID)^
create index IDX_COMPLIANCE_RISK_ON_DEPARTMENT on COMPLIANCE_RISK (DEPARTMENT_ID)^
create index IDX_COMPLIANCE_RISK_ON_RISK_CATEGORY on COMPLIANCE_RISK (RISK_CATEGORY_ID)^
create index IDX_COMPLIANCE_RISK_ON_SOURCE on COMPLIANCE_RISK (SOURCE_ID)^
create index IDX_COMPLIANCE_RISK_ON_RATING on COMPLIANCE_RISK (RATING_ID)^
create index IDX_COMPLIANCE_RISK_ON_PLAN_EVENT on COMPLIANCE_RISK (PLAN_EVENT_ID)^
create index IDX_COMPLIANCE_RISK_ON_OWNER on COMPLIANCE_RISK (OWNER_ID)^
create index IDX_COMPLIANCE_RISK_PLAN_EVENT on COMPLIANCE_RISK (PLAN_EVENT_ID)^
create index IDX_COMPLIANCE_RISK_DEPARTMENT on COMPLIANCE_RISK (DEPARTMENT_ID)^
create index IDX_COMPLIANCE_RISK_RATING on COMPLIANCE_RISK (RATING_ID)^
create index IDX_COMPLIANCE_RISK_OWNER on COMPLIANCE_RISK (OWNER_ID)^
create index IDX_COMPLIANCE_RISK_RISK_CATEGORY on COMPLIANCE_RISK (RISK_CATEGORY_ID)^
create index IDX_COMPLIANCE_RISK_SOURCE on COMPLIANCE_RISK (SOURCE_ID)^
-- end COMPLIANCE_RISK
-- begin COMPLIANCE_POLICY_REQUIREMENT
alter table COMPLIANCE_POLICY_REQUIREMENT add constraint FK_COMPLIANCE_POLICY_REQUIREMENT_ON_COMPLIANCE_POLICY foreign key (COMPLIANCE_POLICY_ID) references COMPLIANCE_POLICY(ID)^
create index IDX_COMPLIANCE_POLICY_REQUIREMENT_ON_COMPLIANCE_POLICY on COMPLIANCE_POLICY_REQUIREMENT (COMPLIANCE_POLICY_ID)^
create index IDX_COMPLIANCE_POLICY_REQUIREMENT_COMPLIANCE_POLICY on COMPLIANCE_POLICY_REQUIREMENT (COMPLIANCE_POLICY_ID)^
-- end COMPLIANCE_POLICY_REQUIREMENT
-- begin COMPLIANCE_POLICY
alter table COMPLIANCE_POLICY add constraint FK_COMPLIANCE_POLICY_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references DEPARTMENT(ID)^
create index IDX_COMPLIANCE_POLICY_ON_DEPARTMENT on COMPLIANCE_POLICY (DEPARTMENT_ID)^
create index IDX_COMPLIANCE_POLICY_DEPARTMENT on COMPLIANCE_POLICY (DEPARTMENT_ID)^
-- end COMPLIANCE_POLICY
-- begin TRAINING
alter table TRAINING add constraint FK_TRAINING_ON_POSITION foreign key (POSITION_ID) references SEC_USER(ID)^
alter table TRAINING add constraint FK_TRAINING_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references DEPARTMENT(ID)^
create index IDX_TRAINING_ON_POSITION on TRAINING (POSITION_ID)^
create index IDX_TRAINING_ON_DEPARTMENT on TRAINING (DEPARTMENT_ID)^
create index IDX_TRAINING_POSITION on TRAINING (POSITION_ID)^
create index IDX_TRAINING_BRANCH on TRAINING (DEPARTMENT_ID)^
-- end TRAINING
-- begin INTERNAL_EXTERNAL_FACTOR_ASSESSMENT
alter table INTERNAL_EXTERNAL_FACTOR_ASSESSMENT add constraint FK_INTERNAL_EXTERNAL_FACTOR_ASSESSMENT_ON_MEASURE_PLAN_ID foreign key (MEASURE_PLAN_ID_ID) references PLAN_EVENT(ID)^
alter table INTERNAL_EXTERNAL_FACTOR_ASSESSMENT add constraint FK_INTERNAL_EXTERNAL_FACTOR_ASSESSMENT_ON_RESPONSIBLE_EXECUTOR foreign key (RESPONSIBLE_EXECUTOR_ID) references SEC_USER(ID)^
alter table INTERNAL_EXTERNAL_FACTOR_ASSESSMENT add constraint FK_INTERNAL_EXTERNAL_FACTOR_ASSESSMENT_ON_SELF_ASSESSMENT_SVK foreign key (SELF_ASSESSMENT_SVK_ID) references SELF_ASSESSMENT_SVK(ID)^
create index IDX_INTERNAL_EXTERNAL_FACTOR_ASSESSMENT_ON_MEASURE_PLAN_ID on INTERNAL_EXTERNAL_FACTOR_ASSESSMENT (MEASURE_PLAN_ID_ID)^
create index IDX_INTERNAL_EXTERNAFACTORASSESSM_ON_RESPONSIBLE_EXECUTOR on INTERNAL_EXTERNAL_FACTOR_ASSESSMENT (RESPONSIBLE_EXECUTOR_ID)^
create index IDX_INTERNAL_EXTERNAL_FACTOR_ASSESSMENT_ON_SELF_ASSESSMENT_SVK on INTERNAL_EXTERNAL_FACTOR_ASSESSMENT (SELF_ASSESSMENT_SVK_ID)^
create index IDX_INTERNAL_EXTERNAL_FACTOR_ASSESSMENT_MEASURE_PLAN on INTERNAL_EXTERNAL_FACTOR_ASSESSMENT (MEASURE_PLAN_ID_ID)^
create index IDX_INTERNAL_EXTERNAL_FACTOR_ASSESSMENT_SELF_ASSESSMENT_SVK on INTERNAL_EXTERNAL_FACTOR_ASSESSMENT (SELF_ASSESSMENT_SVK_ID)^
create index IDX_INTERNAL_EXTERNAL_FACTOR_ASSESSMENT_RESPONSIBLE_EXECUTOR on INTERNAL_EXTERNAL_FACTOR_ASSESSMENT (RESPONSIBLE_EXECUTOR_ID)^
-- end INTERNAL_EXTERNAL_FACTOR_ASSESSMENT
-- begin MONITORING_CLIENTS_ML_TF_RISKS
create index IDX_MONITORING_CLIENTS_MLT_FRISKS_INITIATOR on MONITORING_CLIENTS_ML_TF_RISKS (INITIATOR)^
-- end MONITORING_CLIENTS_ML_TF_RISKS
-- begin COMPLIANCE_LAW_VND
alter table COMPLIANCE_LAW_VND add constraint FK_COMPLIANCE_LAW_VND_ON_COMPLIANCE_LAW foreign key (COMPLIANCE_LAW_ID) references COMPLIANCE_LAW(ID)^
alter table COMPLIANCE_LAW_VND add constraint FK_COMPLIANCE_LAW_VND_ON_VND foreign key (VND_ID) references VND(ID)^
create index IDX_COMPLIANCE_LAW_VND_ON_COMPLIANCE_LAW on COMPLIANCE_LAW_VND (COMPLIANCE_LAW_ID)^
create index IDX_COMPLIANCE_LAW_VND_ON_VND on COMPLIANCE_LAW_VND (VND_ID)^
create index IDX_COMPLIANCE_LAW_VND_COMPLIANCE_LAW on COMPLIANCE_LAW_VND (COMPLIANCE_LAW_ID)^
create index IDX_COMPLIANCE_LAW_VND_VND on COMPLIANCE_LAW_VND (VND_ID)^
-- end COMPLIANCE_LAW_VND
-- begin POLICY_PROCEDURE_ASSESSMENT
alter table POLICY_PROCEDURE_ASSESSMENT add constraint FK_POLICY_PROCEDURE_ASSESSMENT_ON_MEASURE_PLAN foreign key (MEASURE_PLAN_ID) references PLAN_EVENT(ID)^
alter table POLICY_PROCEDURE_ASSESSMENT add constraint FK_POLICY_PROCEDURE_ASSESSMENT_ON_RESPONSIBLE_EXECUTOR foreign key (RESPONSIBLE_EXECUTOR_ID) references SEC_USER(ID)^
alter table POLICY_PROCEDURE_ASSESSMENT add constraint FK_POLICY_PROCEDURE_ASSESSMENT_ON_SELF_ASSESSMENT_SVK foreign key (SELF_ASSESSMENT_SVK_ID) references SELF_ASSESSMENT_SVK(ID)^
create index IDX_POLICY_PROCEDURE_ASSESSMENT_ON_MEASURE_PLAN on POLICY_PROCEDURE_ASSESSMENT (MEASURE_PLAN_ID)^
create index IDX_POLICY_PROCEDURE_ASSESSMENT_ON_RESPONSIBLE_EXECUTOR on POLICY_PROCEDURE_ASSESSMENT (RESPONSIBLE_EXECUTOR_ID)^
create index IDX_POLICY_PROCEDURE_ASSESSMENT_ON_SELF_ASSESSMENT_SVK on POLICY_PROCEDURE_ASSESSMENT (SELF_ASSESSMENT_SVK_ID)^
create index IDX_POLICY_PROCEDURE_ASSESSMENT_RESPONSIBLE_EXECUTOR on POLICY_PROCEDURE_ASSESSMENT (RESPONSIBLE_EXECUTOR_ID)^
create index IDX_POLICY_PROCEDURE_ASSESSMENT_SELF_ASSESSMENT_SVK on POLICY_PROCEDURE_ASSESSMENT (SELF_ASSESSMENT_SVK_ID)^
create index IDX_POLICY_PROCEDURE_ASSESSMENT_MEASURE_PLAN on POLICY_PROCEDURE_ASSESSMENT (MEASURE_PLAN_ID)^
-- end POLICY_PROCEDURE_ASSESSMENT
-- begin SELF_ASSESSMENT_SVK
alter table SELF_ASSESSMENT_SVK add constraint FK_SELF_ASSESSMENT_SVK_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references DEPARTMENT(ID)^
alter table SELF_ASSESSMENT_SVK add constraint FK_SELF_ASSESSMENT_SVK_ON_PERIOD foreign key (PERIOD_ID) references PERIOD(ID)^
alter table SELF_ASSESSMENT_SVK add constraint FK_SELF_ASSESSMENT_SVK_ON_QUARTER foreign key (QUARTER_ID) references RATING(ID)^
alter table SELF_ASSESSMENT_SVK add constraint FK_SELF_ASSESSMENT_SVK_ON_PREVIOUS_RATING foreign key (PREVIOUS_RATING_ID) references RATING(ID)^
alter table SELF_ASSESSMENT_SVK add constraint FK_SELF_ASSESSMENT_SVK_ON_CURRENT_RATING foreign key (CURRENT_RATING_ID) references RATING(ID)^
alter table SELF_ASSESSMENT_SVK add constraint FK_SELF_ASSESSMENT_SVK_ON_FORECAST_RATING foreign key (FORECAST_RATING_ID) references RATING(ID)^
create index IDX_SELF_ASSESSMENT_SVK_ON_DEPARTMENT on SELF_ASSESSMENT_SVK (DEPARTMENT_ID)^
create index IDX_SELF_ASSESSMENT_SVK_ON_PERIOD on SELF_ASSESSMENT_SVK (PERIOD_ID)^
create index IDX_SELF_ASSESSMENT_SVK_ON_QUARTER on SELF_ASSESSMENT_SVK (QUARTER_ID)^
create index IDX_SELF_ASSESSMENT_SVK_ON_PREVIOUS_RATING on SELF_ASSESSMENT_SVK (PREVIOUS_RATING_ID)^
create index IDX_SELF_ASSESSMENT_SVK_ON_CURRENT_RATING on SELF_ASSESSMENT_SVK (CURRENT_RATING_ID)^
create index IDX_SELF_ASSESSMENT_SVK_ON_FORECAST_RATING on SELF_ASSESSMENT_SVK (FORECAST_RATING_ID)^
create index IDX_SELF_ASSESSMENT_SVK_FORECAST_RATING on SELF_ASSESSMENT_SVK (FORECAST_RATING_ID)^
create index IDX_SELF_ASSESSMENT_SVK_DEPARTMENT on SELF_ASSESSMENT_SVK (DEPARTMENT_ID)^
create index IDX_SELF_ASSESSMENT_SVK_QUARTER on SELF_ASSESSMENT_SVK (QUARTER_ID)^
create index IDX_SELF_ASSESSMENT_SVK_CURRENT_RATING on SELF_ASSESSMENT_SVK (CURRENT_RATING_ID)^
create index IDX_SELF_ASSESSMENT_SVK_PREVIOUS_RATING on SELF_ASSESSMENT_SVK (PREVIOUS_RATING_ID)^
create index IDX_SELF_ASSESSMENT_SVK_PERIOD on SELF_ASSESSMENT_SVK (PERIOD_ID)^
-- end SELF_ASSESSMENT_SVK
-- begin PLAN_EVENT_FILE_LINK
alter table PLAN_EVENT_FILE_LINK add constraint FK_PLAEVEFIL_ON_PLAN_EVENT foreign key (PLAN_EVENT_ID) references PLAN_EVENT(ID)^
alter table PLAN_EVENT_FILE_LINK add constraint FK_PLAEVEFIL_ON_FILE_ENTITY foreign key (FILE_ENTITY_ID) references FILE_ENTITY(ID)^
-- end PLAN_EVENT_FILE_LINK
-- begin PLAN_EVENT_FILES
alter table PLAN_EVENT_FILES add constraint FK_PLAEVEFIL_ON_FILE_ENTITY foreign key (FILE_ENTITY_ID) references FILE_ENTITY(ID)^
alter table PLAN_EVENT_FILES add constraint FK_PLAEVEFIL_ON_PLAN_EVENT foreign key (PLAN_EVENT_ID) references PLAN_EVENT(ID)^
-- end PLAN_EVENT_FILES
-- begin ACTIVITY_FILES
alter table ACTIVITY_FILES add constraint FK_ACTFIL_ON_FILE_ENTITY foreign key (FILE_ENTITY_ID) references FILE_ENTITY(ID)^
alter table ACTIVITY_FILES add constraint FK_ACTFIL_ON_ACTIVITY foreign key (ACTIVITY_ID) references ACTIVITY(ID)^
-- end ACTIVITY_FILES
-- begin INCIDENT_FILES
alter table INCIDENT_FILES add constraint FK_INCFIL_ON_INCIDENTS foreign key (INCIDENTS_ID) references INCIDENTS(ID)^
alter table INCIDENT_FILES add constraint FK_INCFIL_ON_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID)^
-- end INCIDENT_FILES
-- begin ACTIVITY_FILE_LINK
alter table ACTIVITY_FILE_LINK add constraint FK_ACTFIL_ON_ACTIVITY foreign key (ACTIVITY_ID) references ACTIVITY(ID)^
alter table ACTIVITY_FILE_LINK add constraint FK_ACTFIL_ON_FILE_ENTITY foreign key (FILE_ENTITY_ID) references FILE_ENTITY(ID)^
-- end ACTIVITY_FILE_LINK
-- begin INCIDENT_DEPARTMENTS
alter table INCIDENT_DEPARTMENTS add constraint FK_INCDEP_ON_INCIDENTS foreign key (INCIDENTS_ID) references INCIDENTS(ID)^
alter table INCIDENT_DEPARTMENTS add constraint FK_INCDEP_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references DEPARTMENT(ID)^
-- end INCIDENT_DEPARTMENTS
