alter table CONFLICT_OF_INTEREST add constraint FK_CONFLICT_OF_INTEREST_ON_PLAN_EVENT foreign key (PLAN_EVENT_ID) references PLAN_EVENT(ID);
alter table CONFLICT_OF_INTEREST add constraint FK_CONFLICT_OF_INTEREST_ON_RISK_LEVEL foreign key (RISK_LEVEL_ID) references RISK_LEVEL(ID);
create index IDX_CONFLICT_OF_INTEREST_ON_PLAN_EVENT on CONFLICT_OF_INTEREST (PLAN_EVENT_ID);
create index IDX_CONFLICT_OF_INTEREST_ON_RISK_LEVEL on CONFLICT_OF_INTEREST (RISK_LEVEL_ID);
create index IDX_CONFLICT_OF_INTEREST_PLAN_EVENT on CONFLICT_OF_INTEREST (PLAN_EVENT_ID);
create index IDX_CONFLICT_OF_INTEREST_RISK_LEVEL on CONFLICT_OF_INTEREST (RISK_LEVEL_ID);
