create table COMPLAINT (
    ID uuid,
    VERSION integer not null,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    DELETE_TS timestamp,
    DELETED_BY varchar(50),
    --
    COMPLAINT_SYSTEM_NUMBER integer,
    COMPLAINT_NUMBER varchar(512),
    RECEIVED_DATE date,
    REGISTRATION_DATE date not null,
    CHANNEL_ID uuid,
    APPLICANT_TYPE_ID uuid,
    CLIENT_PH_ID uuid,
    APPLICANT_LAST_NAME varchar(512),
    APPLICANT_FIRST_NAME varchar(512),
    APPLICANT_IIN varchar(12) not null,
    REASON_ID uuid,
    WORD_ANALYSIS_ENABLED boolean,
    COMPLAINT_SIGN varchar(50),
    DESCRIPTION text,
    REASON_FOR_THE_COMPLAINT text,
    CLOSED_BY_LOGIN_ID uuid,
    CLOSED_BY_USER varchar(1000),
    COMMENT_ text,
    CLOSED_DATE date,
    EMPLOYEE_ID uuid,
    RESPONSIBLE_DEPARTMENT varchar(1000),
    DUE_DATE date,
    RESPONSE_TYPE_ID uuid,
    STATUS integer not null,
    COMPLAINT_REASON_ID uuid,
    RISK_ASSESSMENT_ID uuid,
    COMPLAINT_COMMENT text,
    INITIATOR varchar(255) not null,
    --
    primary key (ID)
);