alter table ACTIVITY add constraint FK_ACTIVITY_ON_PLAN_EVENT foreign key (PLAN_EVENT_ID) references PLAN_EVENT(ID);
alter table ACTIVITY add constraint FK_ACTIVITY_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references DEPARTMENT(ID);
create index IDX_ACTIVITY_ON_PLAN_EVENT on ACTIVITY (PLAN_EVENT_ID);
create index IDX_ACTIVITY_ON_DEPARTMENT on ACTIVITY (DEPARTMENT_ID);
create index IDX_ACTIVITY_PLAN_EVENT on ACTIVITY (PLAN_EVENT_ID);
create index IDX_ACTIVITY_DEPARTMENT on ACTIVITY (DEPARTMENT_ID);
