alter table COMPLIANCE_LAW_ACT add constraint FK_COMPLIANCE_LAW_ACT_ON_COMPLIANCE_LAW foreign key (COMPLIANCE_LAW_ID) references COMPLIANCE_LAW(ID);
alter table COMPLIANCE_LAW_ACT add constraint FK_COMPLIANCE_LAW_ACT_ON_ACT foreign key (ACT_ID) references ACT(ID);
create index IDX_COMPLIANCE_LAW_ACT_ON_COMPLIANCE_LAW on COMPLIANCE_LAW_ACT (COMPLIANCE_LAW_ID);
create index IDX_COMPLIANCE_LAW_ACT_ON_ACT on COMPLIANCE_LAW_ACT (ACT_ID);
create index IDX_COMPLIANCE_LAW_ACT_COMPLIANCE_LAW on COMPLIANCE_LAW_ACT (COMPLIANCE_LAW_ID);
create index IDX_COMPLIANCE_LAW_ACT_ACT on COMPLIANCE_LAW_ACT (ACT_ID);
