alter table RISK_EVENT add constraint FK_RISK_EVENT_ON_SELF_ASSESSMENT_SVK foreign key (SELF_ASSESSMENT_SVK_ID) references SELF_ASSESSMENT_SVK(ID);
alter table RISK_EVENT add constraint FK_RISK_EVENT_ON_PLAN_EVENT foreign key (PLAN_EVENT_ID) references ACTIVITY(ID);
create index IDX_RISK_EVENT_ON_SELF_ASSESSMENT_SVK on RISK_EVENT (SELF_ASSESSMENT_SVK_ID);
create index IDX_RISK_EVENT_ON_PLAN_EVENT on RISK_EVENT (PLAN_EVENT_ID);
create index IDX_RISK_EVENT_PLAN_EVENT on RISK_EVENT (PLAN_EVENT_ID);
create index IDX_RISK_EVENT_SELF_ASSESSMENT_SVK on RISK_EVENT (SELF_ASSESSMENT_SVK_ID);
