alter table COMPLIANCE_LAW_VND add constraint FK_COMPLIANCE_LAW_VND_ON_COMPLIANCE_LAW foreign key (COMPLIANCE_LAW_ID) references COMPLIANCE_LAW(ID);
alter table COMPLIANCE_LAW_VND add constraint FK_COMPLIANCE_LAW_VND_ON_VND foreign key (VND_ID) references VND(ID);
create index IDX_COMPLIANCE_LAW_VND_ON_COMPLIANCE_LAW on COMPLIANCE_LAW_VND (COMPLIANCE_LAW_ID);
create index IDX_COMPLIANCE_LAW_VND_ON_VND on COMPLIANCE_LAW_VND (VND_ID);
create index IDX_COMPLIANCE_LAW_VND_COMPLIANCE_LAW on COMPLIANCE_LAW_VND (COMPLIANCE_LAW_ID);
create index IDX_COMPLIANCE_LAW_VND_VND on COMPLIANCE_LAW_VND (VND_ID);
