alter table TRAINING add constraint FK_TRAINING_ON_POSITION foreign key (POSITION_ID) references SEC_USER(ID);
alter table TRAINING add constraint FK_TRAINING_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references DEPARTMENT(ID);
create index IDX_TRAINING_ON_POSITION on TRAINING (POSITION_ID);
create index IDX_TRAINING_ON_DEPARTMENT on TRAINING (DEPARTMENT_ID);
create index IDX_TRAINING_POSITION on TRAINING (POSITION_ID);
create index IDX_TRAINING_BRANCH on TRAINING (DEPARTMENT_ID);
