alter table FILE_ENTITY add constraint FK_FILE_ENTITY_ON_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID);
create index IDX_FILE_ENTITY_ON_FILE_DESCRIPTOR on FILE_ENTITY (FILE_DESCRIPTOR_ID);
