alter table DEPARTMENT add constraint FK_DEPARTMENT_ON_PARENT foreign key (PARENT_ID) references DEPARTMENT(ID);
create index IDX_DEPARTMENT_ON_PARENT on DEPARTMENT (PARENT_ID);
create index IDX_DEPARTMENT_PARENT on DEPARTMENT (PARENT_ID);
