alter table COMPLIANCE_POLICY add constraint FK_COMPLIANCE_POLICY_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references DEPARTMENT(ID);
create index IDX_COMPLIANCE_POLICY_ON_DEPARTMENT on COMPLIANCE_POLICY (DEPARTMENT_ID);
create index IDX_COMPLIANCE_POLICY_DEPARTMENT on COMPLIANCE_POLICY (DEPARTMENT_ID);
