alter table COMPLAINT_ANALYSIS_LOG add constraint FK_COMPLAINT_ANALYSIS_LOG_ON_COMPLAINT foreign key (COMPLAINT_ID) references COMPLAINT(ID);
alter table COMPLAINT_ANALYSIS_LOG add constraint FK_COMPLAINT_ANALYSIS_LOG_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_COMPLAINT_ANALYSIS_LOG_ON_COMPLAINT on COMPLAINT_ANALYSIS_LOG (COMPLAINT_ID);
create index IDX_COMPLAINT_ANALYSIS_LOG_ON_USER on COMPLAINT_ANALYSIS_LOG (USER_ID);
create index IDX_COMPLAINT_ANALYSIS_LOG_USER on COMPLAINT_ANALYSIS_LOG (USER_ID);
create index IDX_COMPLAINT_ANALYSIS_LOG_COMPLAINT on COMPLAINT_ANALYSIS_LOG (COMPLAINT_ID);
